apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
        - name: calculator
          image: rayudu1889/calculator-microservice:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /operations
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /operations
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
