apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: LoadBalancer   # Use NodePort if LoadBalancer not supported
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
